# Site settings
title: jackson15j.github.io
# email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Craig Astill: Coding from the saddle.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jackson15j.github.io" # the base hostname & protocol for your site
twitter_username: jackson15jj
github_username:  jackson15j

# Build settings
markdown: kramdown
