safe:        false
auto:        true
server:      false
url:         http://jackson15j.github.io
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
future:      true
markdown:    maruku
permalink:   date